# Teleop Basic Param

navigator/takeoffHeight: 0.2
navigator/naviFrameInt: 0  # deprecated?  map frame: 0, body frame: 1 
navigator/mapFrame: map
navigator/targetFrame: target

# Keyboard Teleop

navigator/evenMoveDistance: 0.1
navigator/upDownDistance: 0.1
navigator/forwardBackwardDistance: 0
navigator/leftRightDistance: 0

# Keyboard Teleop
navigator/targetVelRate: 0.5
navigator/targetPitchRollInterval: 0.005  # 0.2 / 20 = 0.01, 0.005 ~ 0.01  m/s
navigator/targetAltInterval: 0.02
navigator/targetYawRate: 0.5 #  0.05 
navigator/cmdVelLev2Gain : 1.5

# for optical flow control
#navigator/xyVelModePosCtrlTakeoff : false