### Differential Flatness PID control for hydrusx hex type

# alt [N]
controller:
        alt:
                offset: 0
                limit: 16.5
                p_term_limit: 16.5
                i_term_limit: 16.5
                d_term_limit: 16.5
                alt_landing_const_i_ctrl_thresh: -0.2
                err_thresh: 0.5

        xy:
                p_gain: 0.1 
                i_gain: 0.005
                hovering_i_gain: 0.001
                d_gain: 0.3
                limit: 0.3 
                p_term_limit: 0.2 
                i_term_limit: 0.15
                d_term_limit: 0.2
                x_offset: 0
                y_offset: 0

        yaw:
                limit: 10.0
                p_term_limit: 10.0
                i_term_limit: 10.0
                d_term_limit: 10.0

