hydrusx:
  servo_controller:
    joints:
      state_sub_topic: /servo/states
      ctrl_pub_topic: /servo/target_states
      torque_pub_topic: /servo/torque_enable
      angle_sgn: 1
      angle_scale: 0.001534
      zero_point_offset: 2047

      # should be in order in terms of kinematics model
      # i.e. joint1 -> jointN
      controller1:
        id: 0
        name: joint1
        # angle_max: 1.58 # you can specify for each controller
      controller2:
        id: 1
        name: joint2
      controller3:
        id: 2
        name: joint3
      controller4:
        id: 3
        name: joint4
      controller5:
        id: 4
        name: joint5

