# Sensor Loader
estimator:
        sensor_no: 3

        sensor_plugin_name1: sensor_plugin/imu
        sensor_plugin_name2: sensor_plugin/mocap
        sensor_plugin_name3: sensor_plugin/optical_flow

