aerial_robot_control_name: aerial_robot_control/over_act_no_servo_delay/nmpc_controller

controller:
  physical: # mini quadrotor with Livox lidar. printed by KDL, and then fill in this section
    mass: 2.99194 # kg
    gravity: 9.798 # m/s^2
    inertia_diag: [ 0.0621273, 0.0927884, 0.130061 ] # kg m^2
    dr1: -1  # direction of motor 1
    p1: [ 0.132567, 0.137668, -0.0154203 ] # position of motor 1
    dr2: 1  # direction of motor 2
    p2: [ -0.142634, 0.137655, -0.0154202 ] # position of motor 2
    dr3: -1  # direction of motor 3
    p3: [ -0.142647, -0.137969, -0.0154203 ] # position of motor 3
    dr4: 1  # direction of motor 4
    p4: [ 0.132585, -0.137979, -0.0154202 ] # position of motor 4
    kq_d_kt: 0.0171998

    t_servo: 0.1 # sec  TODO: check

  nmpc:
    T_samp: 0.025  # 40 Hz  TODO: should be adjusted by main_rate
    T_pred: 2.0  # seconds
    T_integ: 0.1  # seconds

    n_states: 13
    n_controls: 4

    # constraint
    w_max: 6  # 1 rad/s ~ 57 deg/s
    w_min: -6

    v_max: 1
    v_min: -1

    thrust_max: 30 # N
    thrust_min: 0 # N

#    a_max: PI / 2
#    a_min: -PI / 2
    a_max: 0.0
    a_min: 0.0

    # params for the cost function
    Qp_xy: 300  # 0
    Qp_z: 400  # 500
    Qv_xy: 10  # 0
    Qv_z: 10  # 100
    Qq_xy: 10  # 400
    Qq_z: 100
    Qw_xy: 5
    Qw_z: 5
    Qa: 5
    Rt: 1
    Rac: 1

    is_attitude_ctrl: false
    is_body_rate_ctrl: true

    is_print_physical_params: false
    is_debug: false

#  original ----------------------------------------

  torque_allocation_matrix_inv_pub_interval: 0.05
  wrench_allocation_matrix_pub_interval: 0.1
  gimbal_calc_in_fc : false
  wrench_estimate_update_rate: 100
  momentum_observer_force_weight: 3
  momentum_observer_torque_weight: 2.5

  pd_wrench_comp_mode: true

  external_force_upper_limit: 0.0
  external_force_lower_limit: 0.0
  external_torque_upper_limit: 0.0
  external_torque_lower_limit: 0.0
  cutoff_freq: 1.0
  sample_freq: 40.0

  xy:
    p_gain: 1.5
    i_gain: 0.05
    d_gain: 1.0
    limit_sum: 4.0
    limit_p: 12.0
    limit_i: 12.0
    limit_d: 12.0

  z:
    p_gain: 5.0
    i_gain: 1.0
    d_gain: 2.5
    limit_err_p: 1.0
    limit_sum: 25.0 # N for clamping thrust force
    limit_p: 25.0
    limit_i: 25.0
    limit_d: 25.0
    force_landing_descending_rate: -0.5

  roll:
    p_gain: 8.0 #8~25
    i_gain: 1.0
    d_gain: 5.0 #4~11
    limit_sum: 20.0
    limit_p: 20.0
    limit_i: 20.0
    limit_d: 20.0

    start_rp_integration_height: 0.01

  pitch:
    p_gain: 8.0 #8~25
    i_gain: 1.0
    d_gain: 6.0 #4~11
    limit_sum: 20.0
    limit_p: 20.0
    limit_i: 20.0
    limit_d: 20.0

    start_rp_integration_height: 0.01

  yaw:
    p_gain: 7.0
    i_gain: 1.0
    d_gain: 5.0
    limit_err_p: 0.4
    limit_sum: 20.0
    limit_p: 20.0
    limit_i: 20.0
    limit_d: 20.0

    need_d_control: true
