aerial_robot_control_name: aerial_robot_control/over_act_full/nmpc_controller

controller:
  physical:
    mass: 2.99194 # kg
    gravity: 9.798 # m/s^2
    inertia_diag: [ 0.0621273, 0.0927884, 0.130061 ] # kg m^2
    dr1: -1  # direction of motor 1
    p1: [ 0.132567, 0.137668, -0.0154203 ] # position of motor 1
    dr2: 1  # direction of motor 2
    p2: [ -0.142634, 0.137655, -0.0154202 ] # position of motor 2
    dr3: -1  # direction of motor 3
    p3: [ -0.142647, -0.137969, -0.0154203 ] # position of motor 3
    dr4: 1  # direction of motor 4
    p4: [ 0.132585, -0.137979, -0.0154202 ] # position of motor 4
    kq_d_kt: 0.0171998

    # the identified parameters are 1/1.619, 1/1.646, 1/1.530, 1/1.542. so the average is 1/1.584 = 0.6312 s
    t_servo: 0.63 # sec

  nmpc:
    T_samp: 0.025  # 40 Hz  TODO: should be adjusted by main_rate
    T_pred: 2.0  # seconds
    T_integ: 0.1  # seconds

    # constraint
    w_max: 6  # 1 rad/s ~ 57 deg/s
    w_min: -6

    v_max: 1
    v_min: -1

    thrust_max: 30 # N
    thrust_min: 0 # N

    a_max: 1.5708  # 30 degree ~ 0.5    1.5708 rad ~ 90 deg
    a_min: -1.5708

    # params for the cost function
    Qp_xy: 300
    Qp_z: 400
    Qv_xy: 10
    Qv_z: 10
    Qq_xy: 300
    Qq_z: 300
    Qw_xy: 5
    Qw_z: 5
    Qa: 0
    Rt: 1
    Rac_d: 50  # difference of ac

    # for body_rate controller
    roll_rate_p_gain: 0.0
    pitch_rate_p_gain: 0.0
    yaw_rate_p_gain: 0.0

    is_attitude_ctrl: false
    is_body_rate_ctrl: true

    is_print_physical_params: false
    is_debug: false
