aerial_robot_control_name: aerial_robot_control/over_act_full/nmpc_controller

controller:
  physical:
    mass: 2.99194 # kg
    gravity: 9.798 # m/s^2
    inertia_diag: [ 0.0621273, 0.0927884, 0.130061 ] # kg m^2
    dr1: -1  # direction of motor 1
    p1: [ 0.132567, 0.137668, -0.0154203 ] # position of motor 1
    dr2: 1  # direction of motor 2
    p2: [ -0.142634, 0.137655, -0.0154202 ] # position of motor 2
    dr3: -1  # direction of motor 3
    p3: [ -0.142647, -0.137969, -0.0154203 ] # position of motor 3
    dr4: 1  # direction of motor 4
    p4: [ 0.132585, -0.137979, -0.0154202 ] # position of motor 4
    kq_d_kt: 0.0171998

    t_servo: 0.1 # sec  TODO: check

  nmpc:
    T_samp: 0.025  # 40 Hz  TODO: should be adjusted by main_rate
    T_pred: 2.0  # seconds
    T_integ: 0.1  # seconds

    # constraint
    w_max: 6  # 1 rad/s ~ 57 deg/s
    w_min: -6

    v_max: 1
    v_min: -1

    thrust_max: 30 # N
    thrust_min: 0 # N

#    a_max: PI / 2
#    a_min: -PI / 2    30 degree ~ 0.5
    a_max: 0.5
    a_min: -0.5

    # params for the cost function
    Qp_xy: 300  # 0
    Qp_z: 400  # 500
    Qv_xy: 10  # 0
    Qv_z: 10  # 100
    Qq_xy: 10  # 400
    Qq_z: 100
    Qw_xy: 5
    Qw_z: 5
    Qa: 5
    Rt: 1
    Rac: 1

    # for body_rate controller
    roll_rate_p_gain: 0.0
    pitch_rate_p_gain: 0.0
    yaw_rate_p_gain: 0.0

    is_attitude_ctrl: false
    is_body_rate_ctrl: true

    is_print_physical_params: false
    is_debug: false
