motor_info:
        min_pwm: 0.5 # 1000 [ms]
        max_pwm: 0.9 # 1800 [ms]
        min_thrust: 2.0 #  [N]
        force_landing_thrust: 6.0 #[N]
        m_f_rate: -0.0141
        pwm_conversion_mode: 0 # SQRT Mode
        vel_ref_num: 5
        ref1:
                voltage: 24.2
                max_thrust: 21.65 # N 
                polynominal2: 0.101701985 # x10
                polynominal1: -8.642202793  # x10
                polynominal0: 17.2694473690 # x1
        ref2:
                voltage: 23.2
                max_thrust: 20.22 # N 
                polynominal2: 0.126335599 # x10
                polynominal1: -13.112115260  # x10
                polynominal0: 35.7199362487 # x1
        ref3:
                voltage: 22.2
                max_thrust: 18.78 # N 
                polynominal2: 0.113729790 # x10
                polynominal1: -11.648288086 # x10
                polynominal0: 31.2935048877 # x1
        ref4:
                voltage: 21.2
                max_thrust: 17.2 # N 
                polynominal2: 0.100796786 # x10
                polynominal1: -10.150051525 # x10
                polynominal0: 26.7759262629 # x1

        ref5:
                voltage: 20
                max_thrust: 15.78 # N 
                polynominal2: 0.092954097 # x10
                polynominal1: -9.403022168 # x10
                polynominal0: 24.9503518980 # x1