<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="hydrusx_common" >

  <xacro:property name="pi" value="3.1415926535897931" />
  <!-- kinematics [m] -->
  <xacro:property name="link_length" value=".6" />
  <xacro:property name="link_rod_length" value=".528" />
  <xacro:property name="protector_radius" value=".1925" />
  <xacro:property name="link_joint_offset" value="0.3" />
  <xacro:property name="rotor_radius" value=".02" />
  <xacro:property name="rotor_height" value=".05" />
  <xacro:property name="bat_offset" value="0.0" />
  <xacro:property name="head_leg_offset" value="-0.25" />
  <xacro:property name="end_leg_offset" value="0.235" />

  <!-- inertial paramters -->
  <!-- mass [Kg] -->
  <xacro:property name="link_rod_mass" value="0.099" />
  <xacro:property name="link_center_mass" value=".211" />
  <xacro:property name="joint_mass" value=".19" /> <!-- rollor: 0.15 -->
  <xacro:property name="protector_mass" value=".05" />
  <xacro:property name="protector_holder_mass" value=".0386" />
  <xacro:property name="bat_mass" value="0.193" /> <!-- hyperon: 0.41, white(2700mAh): 0.364, white(1300mAh): 0.193 -->

  <xacro:property name="head_leg_mass" value="0.045" /> <!-- rollor: 0.017 -->
  <xacro:property name="end_leg_mass" value="0.073" /> <!-- rollor: 0.017 -->
  <xacro:property name="rotor_mass" value=".05" /> <!-- exclude from center mass -->

  <!-- collision model parameter -->
  <xacro:property name="collision_model_height" value="0.14" />
  <xacro:property name="collision_model_z_offset" value="-0.0215" />

  <!-- inertial [N*m*m] -->
  <xacro:property name="link_rod_inertia" value="${link_rod_mass * link_rod_length * link_rod_length /12}" /> <!-- mass * dist * dist -->
  <xacro:property name="protector_inertia" value="${protector_mass * protector_radius * protector_radius}" /> <!-- mass * dist * dist -->
  <xacro:property name="protector_holder_inertia" value="${protector_holder_mass * protector_radius * protector_radius}" /> <!-- mass * dist * dist -->

  <!-- dynamics -->
  <xacro:property name="max_force" value="18" /> <!-- [N] -->

  <xacro:macro name="link_model" params="type">
    <!-- for fcl in planning -->
    <collision>
      <origin rpy="0 0 0" xyz="${link_length* 0.5} 0 ${collision_model_z_offset}"/>
      <geometry>
        <box size="${link_length} 0.05 ${collision_model_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin rpy="${-pi/2} 0 0" xyz="${link_length* 0.5} 0 0"/>
      <geometry>
        <mesh filename="package://hydrus/urdf/mesh/link/${type}_link.dae"/>
      </geometry>
    </visual>
  </xacro:macro>

  <xacro:macro name="extra_module" params="name parent *origin *inertial visible:=0 model_url:=0">
    <joint name="${parent}2${name}" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}"/>
      <xacro:insert_block name="origin" />
    </joint>
    <link name="${name}">
      <xacro:insert_block name="inertial" />
      <xacro:if value="${visible == 1}">
        <visual>
          <!-- the origin of link_frame and visual_frame should be identical -->
          <origin rpy="${-pi/2} 0 0" xyz="0 0 0"/>
          <geometry>
            <mesh filename="${model_url}"/>
          </geometry>
        </visual>
        </xacro:if>
    </link>
  </xacro:macro>

  <!-- friction -->
  <xacro:macro name="friction" params="self">
    <gazebo reference="link${self}">
      <mu1>0.1</mu1>
      <mu2>0.1</mu2>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="damping_factor" params="link">
    <gazebo reference="${link}">
      <dampingFactor>0.00</dampingFactor>
    </gazebo>
  </xacro:macro>
</robot>
