#HydrusX Quad config

/motor_info:
        motor_num: 4

control_rate: 10.0
root_link: 3 #from 1

# Link
link_num: 4
link_length: 0.6
link_base_rod_length: 0.528
link_base_center_mass: 0.4046 # 210.6[g], no battery; bat1300mAh: 194[g]
link_base_rod_common_mass: 0.099

# Protector
ring_radius: 0.1925
link_base_two_ring_holder_mass: 0.0386
link_base_ring_mass: 0.05 

# Joint
joint_num: 3
link_joint_offset: -0.3
link_joint_mass: 0.2075
joint1_base_link: 1 #link2
joint2_base_link: 2 #link3
joint3_base_link: 3 #link4

# Extra Module
extra_module_num: 5

# MCU: d_board
extra_module1_link: 2
extra_module1_offset: -0.280
extra_module1_mass: 0.03 #board: 0.045, odroid-usb-cable: 0.01; tx1-usb-cable: 0.0072

# PC
extra_module2_link: 1
extra_module2_offset: 0.220
extra_module2_mass: 0.24 # TX1 Orbitty Carrier Board 0.24, Odroid: 0.1

# Additional Leg
# tail
extra_module3_link: 3
extra_module3_offset: 0.235
extra_module3_mass: 0.0623

# head
extra_module4_link: 0
extra_module4_offset: -0.247
extra_module4_mass: 0.0623

# sensors (gps, leddarone, zed )
extra_module5_link: 2
extra_module5_offset: -0.215
extra_module5_mass: 0.06

rotor1_direction: -1 #default: -1
rotor2_direction: 1 #default: 1
rotor3_direction: -1
rotor4_direction: 1 #default :1

q_roll: 400
q_roll_d: 40
q_roll_i: 10.0
q_pitch: 400
q_pitch_d: 40
q_pitch_i: 10.0

q_yaw: 200
strong_q_yaw: 200
q_yaw_d:  100
q_yaw_i: 0.1

q_z: 10.0
q_z_d: 10.0
q_z_i: 10.0

r1: 1.0
r2: 1.0
r3: 1.0
r4: 1.0

dist_thre: 0.06 # 0.17 is max now for planning, 0.06 is enough for l, s pose
f_max: 16.5
f_min: 2.0
