#HydrusX Quad config

control_rate: 10.0

link_num: 4
root_link: 3 #from 1

link_length: 0.6
link_base_rod_length: 0.528
ring_radius: 0.1925
link_joint_offset: 0.3
link_base_rod_mid_mass: 0.099
link_base_ring_mass: 0.05 
link_base_two_ring_holder_mass: 0.0386
link_base_center_mass: 0.2106 # 210.6[g], no battery
link_joint_mass: 0.2075

# Extra Module
extra_module_num: 9

# MCU: d_board
extra_module1_link: 2
extra_module1_offset: 0.240
extra_module1_mass: 0.052 #board: 0.045, usb-cable: 0.0072

# PC
extra_module2_link: 2
extra_module2_offset: 0.220
extra_module2_mass: 0.240 # TX1 Orbitty Carrier Board

# Camera
extra_module3_link: 1
extra_module3_offset: -0.235
extra_module3_mass: 0.147 # PointGrey Fisheye

# Additional Leg
extra_module4_link: 3
extra_module4_offset: -0.235
extra_module4_mass: 0.0623

extra_module5_link: 0
extra_module5_offset: 0.247
extra_module5_mass: 0.0623

# Leg shift at center joint
extra_module6_link: 2
extra_module6_offset: 0.240
extra_module6_mass: -0.04

extra_module7_link: 2
extra_module7_offset: 0.157
extra_module7_mass: 0.0623

# Battery
extra_module8_link: 0
extra_module8_offset: 0
extra_module8_mass: 0.3657

extra_module9_link: 3
extra_module9_offset: 0
extra_module9_mass: 0.3657



propeller1_direction: -1
propeller1_order: 0

propeller2_direction: 1
propeller2_order: 1

propeller3_direction: -1
propeller3_order: 2

propeller4_direction: 1
propeller4_order: 3

q_roll: 400
q_roll_d: 40
q_roll_i: 10.0
q_pitch: 400
q_pitch_d: 40
q_pitch_i: 10.0

q_yaw: 50
strong_q_yaw: 100
q_yaw_d:  100
q_yaw_i: 0.1

q_z: 10.0
q_z_d: 10.0
q_z_i: 10.0

r1: 1.0
r2: 1.0
r3: 1.0
r4: 1.0

dist_thre: 0.06 # 0.17 is max now for planning, 0.06 is enough for l, s pose
f_max: 16.5
f_min: 2.0
