# Kawasaki IMU Board

# flight mode 
kalmanFilterXAxisInputSigma: 0.04
kalmanFilterXAxisBiasSigma: 0.03

# hand mode
#kalmanFilterXAxisInputSigma: 0.03
#kalmanFilterXAxisBiasSigma: 0.0006

kalmanFilterXAxisMeasureSigma: 0.04

# flight mode 
kalmanFilterYAxisInputSigma: 0.04
kalmanFilterYAxisBiasSigma: 0.03

# hand mode
#kalmanFilterYAxisInputSigma: 0.03
#kalmanFilterYAxisBiasSigma: 0.0006


kalmanFilterYAxisMeasureSigma: 0.04

# flight mode 
kalmanFilterZAxisInputSigma: 0.05
kalmanFilterZAxisBiasSigma: 0.0005

# hand mode
#kalmanFilterZAxisInputSigma: 0.025
#kalmanFilterZAxisBiasSigma: 0.0005

kalmanFilterZAxisMeasureSigma: 0.005
kalmanFilterYawInputSigma: 0.05
kalmanFilterYawBiasSigma: 0.004
kalmanFilterYawMeasureSigma: 0.004

