###　現状: kawasaki board's imuはノイズさえなければ、non-biasモードでも綺麗な推定ができるという特徴があり、これはドイツのクワッドコプターではできないことである。
###        特に, z-axisはasctec pelicanのarm-cortexの上にスペサーで固定するだけでも、non-baisフィルタでかなりよい値が得られます。sigma: 0.12-0.003-0.0005 
###

# Kawasaki IMU Board

# x axis
kalman_filter/X/inputSigma: 0.05
kalman_filter/X/biasSigma: 0.05
kalman_filter/X/measureSigma: 0.04

# y axis
kalman_filter/Y/inputSigma: 0.05
kalman_filter/Y/biasSigma: 0.05
kalman_filter/Y/measureSigma: 0.04

# z axis
kalman_filter/Z/inputSigma: 0.35 
kalman_filter/Z/biasSigma: 0.003 
kalman_filter/Z/measureSigma: 0.005

#yaw axis
#kalmanFilterYawInputSigma: 0.1
#kalmanFilterYawBiasSigma: 0.001
#: 0.004

