#HydraX Penta config

link_num: 5
root_link: 3

link_length: 0.6
link_base_rod_length: 0.528
ring_radius: 0.1925
link_joint_offset: 0.3
link_base_rod_mid_mass: 0.099
link_base_ring_mass: 0.05 
link_base_two_ring_holder_mass: 0.0386
link_base_center_mass: 0.4046 # 210.6[g] + 1300[mAh]: 194[g]
#link_base_center_mass: 0.5745 # 210.6[g] + 2700[mAh]:363.9[g]
link_joint_mass: 0.1675

# Extra Module
# MCU: d_board
extra_module1_link: 2
extra_module1_offset: -0.227
extra_module1_mass: 0.022
# PC
extra_module2_link: 3
extra_module2_offset: 0.233
extra_module2_mass: 0.100 # Odroid XU4:

propeller1_direction: -1
propeller1_order: 0

propeller2_direction: 1
propeller2_order: 1

propeller3_direction: -1
propeller3_order: 2

propeller4_direction: 1
propeller4_order: 3

propeller5_direction: -1
propeller5_order: 4


lqi_thread_rate: 20.0
q_roll: 100.0  #  100
q_roll_d: 100.0  #  100
q_roll_i: 10.0 #  10
q_pitch: 100.0  #  100
q_pitch_d: 100.0  #  100
q_pitch_i: 10.0 #  10

q_yaw: 10.0 # 10 
q_yaw_d: 10.0 #  10
q_yaw_i: 1 # 1

q_z: 1.0
q_z_d: 1.0
q_z_i: 1.0

r1: 1.0
r2: 1.0
r3: 1.0
r4: 1.0
r5: 1.0

dist_thre: 0.06 # 0.12 is max now for planning, 0.06 is enough for l, s pose
f_max: 16.5
f_min: 2.0
