bridge_rate: 50
joint_num: 3
bridge_mode: 1

# need to be ordered as the serial link
joint/1/name: joint1
joint/1/angle_max: 1.58
joint/1/angle_min: -1.58
joint/1/angle_sgn: 1
joint/1/angle_scale: 0.001534
joint/1/angle_offset: 2047

joint/2/name: joint2
joint/2/angle_max: 1.58
joint/2/angle_min: -1.58
joint/2/angle_sgn: 1
joint/2/angle_scale: 0.001534
joint/2/angle_offset: 2040

joint/3/name: joint3
joint/3/angle_max: 1.58
joint/3/angle_min: -1.58
joint/3/angle_sgn: 1
joint/3/angle_scale: 0.001534
joint/3/angle_offset: 2047
