verbose: false

downward_camera_image_topic_name: /downward_cam/camera/image
downward_camera_info_topic_name: /downward_cam/camera/camera_info
imu_topic_name: /raw_imu
sonar_topic_name: /sonar_height
odometry_topic_name: /ground_truth/state

image_crop_scale: 0.7
image_cut_pixel: 10
max_count: 200
camera_roll_offset: 3.1415
camera_pitch_offset: 0.0
camera_yaw_offset: -1.5707

use_sonar: false
sonar_offset: 0.0
