sensor_plugin:
        imu:
                imu_board: 1 #d_board
                imu_topic_name: /imu
                level_acc_noise_sigma: 0.06
                z_acc_noise_sigma: 0.05 #real:0.05
                acc_bias_noise_sigma: 0.001 #0.005#0.04
                calib_time: 0.5
