sensor_plugin:
        imu:
                imu_topic_name: /imu
                imu_board: 0 # 0: kduino, 1: d_imu
                level_acc_noise_sigma: 0.06
                z_acc_noise_sigma: 0.05 #real:0.05
                acc_bias_noise_sigma: 0.001 #0.005#0.04

                #when use mocap, please use mocap yaw for acc transform
                yaw_acc_trans_for_experiment_estimation: 1
                