sensor:
        optical_flow:
                start_lower_thre: 0.305 
                start_upper_thre: 0.4  #0.46
                start_vel: 0.2 #0.75 #0.25  

                level_vel_noise_sigma: 0.1
                sonar_noise_sigma:  0.02

                y_axis_direction: -1.0
