sensor:
        optical_flow:
                # EGOMOTION_ESTIMATION_MODE = 0
                # GROUND_TRUTH_MODE = 1
                # EXPERIMENT_MODE = 2
                estimate_mode: 2 # 1 << 1       
                start_lower_thre: 0.305 
                start_upper_thre: 0.4  #0.46
                start_vel: 0.75 #0.25  

                level_vel_noise_sigma: 0.1
                sonar_noise_sigma:  0.01

                y_axis_direction: -1.0
