<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="hydrus3_link" >

  <!-- D-H kai description(different from prof.nakamura) -->

  <xacro:macro name="hydrus3_link" params="self child general fc pc">

    <!-- link -->
    <link name="link${self}">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.0000001"/>
        <inertia
            ixx="0.00000001" ixy="0.0" ixz="0.0"
            iyy="0.00000001" iyz="0.0"
            izz="0.00000002"/>
      </inertial>
    </link>

    <joint name="link${self}2center" type="fixed">
      <parent link="link${self}"/>
      <child link="link${self}_center"/>
      <origin rpy="0 0 0" xyz="${link_length* 0.5} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <link name="link${self}_center">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${link_rod_mass + link_center_mass + protector_mass + protector_holder_mass - rotor_mass}" /> <!-- exclude from center mass -->
        <inertia
            ixx="${protector_inertia / 2}" ixy="0.0" ixz="0.0"
            iyy="${link_rod_inertia + protector_holder_inertia + protector_inertia /2}" iyz="0.0"
            izz="${link_rod_inertia + protector_holder_inertia + protector_inertia}"/>
      </inertial>

      <!-- sepcial inertia & visual & collision -->
      <!-- head -->
      <xacro:if value="${self == 1}">
        <xacro:link_model type="1" />
      </xacro:if>

      <!-- tail -->
      <xacro:if value="${self == child}">
        <xacro:link_model type="4" />
      </xacro:if>

      <!-- fc -->
      <xacro:if value="${fc}">
        <xacro:link_model type="2" />
      </xacro:if>

      <!-- pc: no -->

      <!-- general -->
      <xacro:if value="${general}">
        <xacro:link_model type="3" />
      </xacro:if>
    </link>
    <xacro:damping_factor link ="link${self}"/>

    <!-- rotor -->
    <joint name="rotor${self}" type="continuous">
      <limit effort="100.0" lower="0" upper="${max_force}" velocity="0.5"/> <!-- force range -->
      <parent link="link${self}_center"/>
      <child link="propeller${self}"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <link name="propeller${self}">
      <!-- visual & collisiont -->
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${rotor_mass}"/>
        <inertia
            ixx="${rotor_mass * .25 * rotor_radius * rotor_radius}" ixy="0.0" ixz="0.0"
            iyy="${rotor_mass * .25 * rotor_radius * rotor_radius}" iyz="0.0"
            izz="${rotor_mass * .5 * rotor_radius * rotor_radius}"/>
      </inertial>
    </link>
    <xacro:damping_factor link ="propeller${self}"/>

    <!-- extra module -->
    <!-- pc -->
    <xacro:if value="${pc}">
      <xacro:extra_module name = "pc" parent = "${self}" mass = "${pc_mass}" offset = "${link_length* 0.5 + pc_offset}" />
    </xacro:if>

    <!-- fc -->
    <xacro:if value="${fc}">
      <xacro:extra_module name = "fc" parent = "${self}" mass = "${fc_mass}" offset = "${link_length* 0.5 + fc_offset}" />
    </xacro:if>

    <!-- joint -->
    <xacro:unless value="${self == child}">
      <joint name="joint${self}" type="revolute">
        <limit effort="3.1" lower="-1.57" upper="1.57" velocity="0.5"/>
        <parent link="link${self}"/>
        <child link="link${child}"/>
        <origin rpy="0 0 0" xyz="${link_length} 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.8" friction="0.05"/>
      </joint>

      <xacro:extra_module name = "joint${self}_module" parent = "${child}" mass = "${joint_mass}" offset = "${link_length* 0.5 + link_joint_offset}" /> <!-- special -->
    </xacro:unless>

    <!-- hardware interface -->
    <xacro:unless value="${self == child}">
      <transmission name="joint_tran${self}">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint${self}">
          <!-- TODO: effort is torque, maybe position is enough -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="servo{self}">
          <!-- TODO: effort is torque, maybe position is enough -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>
    </xacro:unless>

    <transmission name="rotor_tran${self}">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="rotor${self}">
        <!-- TODO: effort is torque, maybe position is enough -->
        <hardwareInterface>RotorInterface</hardwareInterface>
      </joint>
      <actuator name="rotor${self}">
        <!-- TODO: effort is torque, maybe position is enough -->
        <hardwareInterface>RotorInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <xacro:friction self ="${self}"/>

  </xacro:macro>

</robot>
