<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="hydrus3_common" >

  <xacro:property name="pi" value="3.1415926535897931" />
  <!-- kinematics [m] -->
  <xacro:property name="link_length" value=".44" />
  <xacro:property name="link_rod_length" value=".4" />
  <xacro:property name="protector_radius" value=".1425" />
  <xacro:property name="link_joint_offset" value="-0.205" />
  <xacro:property name="rotor_radius" value=".015" />
  <xacro:property name="rotor_height" value=".05" />
  <xacro:property name="pc_offset" value="-0.189" /> <!-- from link_cetner -->
  <xacro:property name="fc_offset" value="0.166" /> <!-- from link_cetner -->

  <!-- inertial parameter -->
  <!-- mass [Kg] -->
  <xacro:property name="link_rod_mass" value="0.1" />
  <xacro:property name="link_center_mass" value=".241" />
  <xacro:property name="joint_mass" value=".0785" />
  <xacro:property name="protector_mass" value=".048" />
  <xacro:property name="protector_holder_mass" value=".047" />
  <xacro:property name="fc_mass" value=".022" />
  <xacro:property name="pc_mass" value=".104" />
  <xacro:property name="rotor_mass" value=".05" /> <!-- exclude from center mass -->

  <!-- inertial [N*m*m] -->
  <xacro:property name="link_rod_inertia" value="${link_rod_mass * link_rod_length * link_rod_length /12}" /> <!-- mass * dist * dist -->
  <xacro:property name="protector_inertia" value="${protector_mass * protector_radius * protector_radius}" /> <!-- mass * dist * dist -->
  <xacro:property name="protector_holder_inertia" value="${protector_holder_mass * protector_radius * protector_radius}" /> <!-- mass * dist * dist -->

  <!-- dynamics [N] -->
  <xacro:property name="max_force" value="10" /> <!-- [m] -->

  <xacro:macro name="link_model" params="type">
    <collision>
      <origin rpy="0 0 0" xyz="${link_length* 0.5} 0 0"/>
      <geometry>
        <cylinder length="0.13" radius="${protector_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin rpy="${-pi/2} 0 0" xyz="${link_length* 0.5} 0 0"/>
      <geometry>
        <mesh filename="package://aerial_robot_model/urdf/hydrus3/mesh/hydrus3_link${type}.dae"/>
      </geometry>
    </visual>
  </xacro:macro>

  <xacro:macro name="extra_module" params="name parent mass offset">
    <joint name="link2${name}" type="fixed">
      <parent link="link${parent}"/>
      <child link="${name}"/>
      <origin rpy="0 0 0" xyz="${offset} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="${name}">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia
            ixx="0.00001" ixy="0.0" ixz="0.0"
            iyy="0.00001" iyz="0.0"
            izz="0.00002"/>
      </inertial>
    </link>
  </xacro:macro>

  <!-- friction -->
  <xacro:macro name="friction" params="self">
    <gazebo reference="link${self}">
      <mu1>0.0001</mu1>
      <mu2>0.0001</mu2>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="damping_factor" params="link">
    <gazebo reference="${link}">
      <dampingFactor>0.00</dampingFactor>
    </gazebo>
  </xacro:macro>

</robot>
