### IIR Filter

slam/slam_rx_freq_x: 40
slam/slam_rx_freq_y: 40
slam/slam_rx_freq_z: 40
slam/slam_rx_freq_theta: 40
slam/slam_rx_freq_phy: 40
slam/slam_rx_freq_psi: 40
slam/slam_cutoff_pos_freq_x: 15
slam/slam_cutoff_pos_freq_y: 15
slam/slam_cutoff_pos_freq_z: 15
slam/slam_cutoff_pos_freq_theta: 15
slam/slam_cutoff_pos_freq_phy: 15
slam/slam_cutoff_pos_freq_psi: 15
slam/slam_cutoff_vel_freq_x: 4.4
slam/slam_cutoff_vel_freq_y: 4.3
slam/slam_cutoff_vel_freq_z: 4.3
slam/slam_cutoff_vel_freq_theta: 4.3
slam/slam_cutoff_vel_freq_phy: 4.3
slam/slam_cutoff_vel_freq_psi: 10
slam/slam_filter_vel_val_thre_x: 1
slam/slam_filter_vel_val_thre_y: 1
slam/slam_filter_vel_val_thre_z: 1
slam/slam_filter_vel_val_thre_theta: 1
slam/slam_filter_vel_val_thre_phy: 1
slam/slam_filter_vel_val_thre_psi: 1
slam/slam_filter_vel_change_rate_thre_x: 2
slam/slam_filter_vel_change_rate_thre_y: 2
slam/slam_filter_vel_change_rate_thre_z: 2
slam/slam_filter_vel_change_rate_thre_theta: 2
slam/slam_filter_vel_change_rate_thre_phy: 2
slam/slam_filter_vel_change_rate_thre_psi: 2

