# Mirror Laser Module

mirror/mirror_rx_freq: 40 #<!-- same with hokuyo -->
mirror/mirror_cutoff_pos_freq: 15
mirror/mirror_cutoff_vel_freq: 10
mirror/mirror_filter_vel_change_rate_thre: 2
mirror/mirror_filter_vel_val_thre: 1
mirror/mirror_z_offset_upper_limit: 0.3  #<!-- for asctec 0.4, for rook1 0.32, for rook2_non_leg : 0.3, for rook2_leg : 0.46-->
mirror/mirror_z_offset_lower_limit: 0.18  #<!-- for asctec 0.3, for rook1 0.22, for rook2_non_leg : 0.2, for rook2_leg : 0.36-->

