# Optical Flow Kalman Filter on Kawasaki IMU Board

/quadcopter_node/kalman_filter/XOpt/input_sigma: 0.16 #0.05
/quadcopter_node/kalman_filter/XOpt/bias_sigma: 0.002 #0.005 test 0.002 good
/quadcopter_node/kalman_filter/XOpt/measure_sigma: 0.1

/quadcopter_node/kalman_filter/YOpt/input_sigma: 0.16 #0.05
/quadcopter_node/kalman_filter/YOpt/bias_sigma: 0.002 #0.005 test 0.002 good
/quadcopter_node/kalman_filter/YOpt/measure_sigma: 0.1

/quadcopter_node/kalman_filter/ZOpt/input_sigma: 0.35
/quadcopter_node/kalman_filter/ZOpt/bias_sigma: 0.0006
/quadcopter_node/kalman_filter/ZOpt/measure_sigma: 0.01
