# Rocket Start 

# rocket start & free fall have prefix of navigator/controller

controller/throttle/rocket_start_init_value: 1445 #  please change here for laser mounting module 

# 1530  : nuc + optical + 6000mAhm; 1445: nuc + optical flow + 2650mAh
############### old parma##################
# 1520 for no laser; 1560 for laser mounted 
# 1535:  nuc + optical within high voltage level; 1550 ~ 1560: nuc + optical within low voltage level
# 1550: hokuyo + nuc + 2650mAh within all voltage range, and within higher level of voltage range for hokuyo + nuc + optical sensor
# 1580: hokuyo + nuc + optical + 2650mAh

controller/throttle/rocket_start_init_increment_value: 5 
controller/throttle/rocket_start_step_value: 1 # prev:1
navigator/rocket_start_lower_thre: 0.305 
navigator/rocket_start_upper_thre: 0.46  #0.4
navigator/rocket_start_vel: 0.25  

# _free _fall

navigator/free_fall_thre: 0.28 # 0.2 ~ 0.4 (0.25 for laser; 0.35 for sonar), finally estimate using baro 
controller/throttle/free_fall_step_value: 3  # 2: hokuyo + nuc + px4; 3: px4 + nuc
controller/throttle/motor_stop_value: 1340  # 1470: hokuyo + nuc + px4; 1440: nuc + px4 + 6000mAh; 1340: nuc + px4 + 2650mAh
