# Kalman Filter Parameter for Simulation

/quadcopter_node/kalman_filter/Debug1/inputSigma : 0.16
/quadcopter_node/kalman_filter/Debug1/biasSigma : 0.03  #<!-- 0.006 -->
/quadcopter_node/kalman_filter/Debug1/measureSigma : 0.08
/quadcopter_node/kalman_filter/Debug2/inputSigma : 0.04
/quadcopter_node/kalman_filter/Debug2/biasSigma : 0.03  #<!-- 0.006 -->
/quadcopter_node/kalman_filter/Debug2/measureSigma : 0.04
