# overwrite parameter for simulation

/sensor_plugin:
        mocap:
                ground_truth_sub_name: /hydrus_xi/ground_truth
        gps:
                estimate_mode: 4 #1 << 2
                ned_flag: true # hector_gazebo_plugins/GPS
