#HydrusX Hex config

/motor_info:
        motor_num: 6

control_rate: 15.0

only_three_axis_mode: false
link_num: 6
root_link: 4 #from 1

# Link
link_length: 0.6
link_base_rod_length: 0.528
link_base_center_mass: 0.211 #no battery, motor, propeller etc
link_base_rod_common_mass: 0.099

# Protector
ring_radius: 0.1925
link_base_two_ring_holder_mass: 0.0386
link_base_ring_mass: 0.05 

# Joint
joint_num: 5
link_joint_offset: -0.3
link_joint_mass: 0.2075
joint1_base_link: 1 #link2
joint2_base_link: 2 #link3
joint3_base_link: 3 #link4
joint4_base_link: 4 #link5
joint5_base_link: 5 #link6

# Extra Module
extra_module_num: 12

# MCU: d_board
extra_module1_link: 3
extra_module1_offset: -0.260
extra_module1_mass: 0.03

# PC(hydrus_c: odroid xu4)
extra_module2_link: 2
extra_module2_offset: 0.220
extra_module2_mass: 0.1

# Batteries (four)
extra_module3_link: 0
extra_module3_offset: 0.0 
extra_module3_mass: 0.411 # bat1300mAh: 193[g]; bat3000mAh: 411[g]

extra_module4_link: 1
extra_module4_offset: 0.0 
extra_module4_mass: 0.411 # bat1300mAh: 193[g]; bat3000mAh: 411[g]

extra_module5_link: 4
extra_module5_offset: 0.0 
extra_module5_mass: 0.411 # bat1300mAh: 193[g]; bat3000mAh: 411[g]

extra_module6_link: 5
extra_module6_offset: 0.0 
extra_module6_mass: 0.411 # bat1300mAh: 193[g]; bat3000mAh: 411[g]

# Additional Leg
## HEAD
extra_module7_link: 0
extra_module7_offset: -0.25
extra_module7_mass: 0.0623

## TAIL
extra_module8_link: 5
extra_module8_offset: 0.235
extra_module8_mass: 0.09 # 0.0623 + 5V DC-DC converter

# Sensors
## GPS + Leddar One
extra_module9_link: 3
extra_module9_offset: -0.215
extra_module9_mass: 0.065 

## ZED Stereo
extra_module10_link: 3
extra_module10_offset: -0.01
extra_module10_mass: 0.18 # 0.196 - 0.016(usb cable)

## PC(hydrus_v: tx1)
extra_module11_link: 2
extra_module11_offset: -0.2
extra_module11_mass: 0.24 

## CABLES(hydrus_c - hydrus_v: usb, eth)
extra_module12_link: 2
extra_module12_offset: 0.0
extra_module12_mass: 0.03
extra_module12_iyy: 0.001
extra_module12_izz: 0.001


rotor1_direction: -1
rotor2_direction: 1
rotor3_direction: -1
rotor4_direction: 1
rotor5_direction: -1
rotor6_direction: 1

q_roll: 400
q_roll_d: 40
q_roll_i: 10.0
q_pitch: 400
q_pitch_d: 40
q_pitch_i: 10.0

q_yaw: 50
strong_q_yaw: 200
q_yaw_d:  100
q_yaw_i: 0.4

q_z: 10.0
q_z_d: 10.0
q_z_i: 10.0

r1: 1.0
r2: 1.0
r3: 1.0
r4: 1.0
r5: 1.0
r6: 1.0

dist_thre: 0.15 # 0.17 is max now for planning, 0.06 is enough for l, s pose
f_max: 16.5
f_min: 2.0
