#HydrusX Hex config

control_rate: 15.0

link_num: 6
root_link: 4 #from 1

link_length: 0.6
link_base_rod_length: 0.528
ring_radius: 0.1925
link_joint_offset: 0.3
link_base_rod_mid_mass: 0.099
link_base_ring_mass: 0.05 
link_base_two_ring_holder_mass: 0.0386
link_base_center_mass: 0.4046 # 210.6[g] + 1300[mAh]: 194[g]
#link_base_center_mass: 0.5745 # 210.6[g] + 2700[mAh]:363.9[g]
link_joint_mass: 0.2075

# Extra Module
extra_module_num: 4

# MCU: d_board
extra_module1_link: 3
extra_module1_offset: 0.233
extra_module1_mass: 0.055 #board: 0.045, usb-cable: 0.01
# PC
extra_module2_link: 2
extra_module2_offset: -0.227
extra_module2_mass: 0.1 #0.100 # Odroid XU4

# Additional Leg
extra_module3_link: 5
extra_module3_offset: -0.235
extra_module3_mass: 0.0623

extra_module4_link: 0
extra_module4_offset: 0.247
extra_module4_mass: 0.0623

propeller1_direction: -1
propeller1_order: 0

propeller2_direction: 1
propeller2_order: 1

propeller3_direction: -1
propeller3_order: 2

propeller4_direction: 1
propeller4_order: 3

propeller5_direction: -1
propeller5_order: 4

propeller6_direction: 1
propeller6_order: 5

q_roll: 400 
q_roll_d: 40.0
q_roll_i: 10.0
q_pitch: 400 
q_pitch_d: 40.0
q_pitch_i: 10.0

q_yaw: 100
strong_q_yaw: 200
q_yaw_d: 100.0
q_yaw_i: 0.4

q_z: 10.0
q_z_d: 10.0
q_z_i: 10.0

r1: 1.0
r2: 1.0
r3: 1.0
r4: 1.0
r5: 1.0
r6: 1.0

dist_thre: 0.17 # 0.17 is max now for planning, 0.06 is enough for l, s pose
f_max: 16.5
f_min: 2.0
