bridge_rate: 50
joint_num: 5
bridge_mode: 1

# need to be ordered as the serial link
joint/1/angle_max: 1.58
joint/1/angle_min: -1.58
joint/1/angle_sgn: 1
joint/1/angle_scale: 0.001534
joint/1/angle_offset: 2073

joint/2/angle_max: 1.58
joint/2/angle_min: -1.58
joint/2/angle_sgn: 1
joint/2/angle_scale: 0.001534
joint/2/angle_offset: 2054

joint/3/angle_max: 1.58
joint/3/angle_min: -1.58
joint/3/angle_sgn: 1
joint/3/angle_scale: 0.001534
joint/3/angle_offset: 2001

joint/4/angle_max: 1.58
joint/4/angle_min: -1.58
joint/4/angle_sgn: 1
joint/4/angle_scale: 0.001534
joint/4/angle_offset: 2071

joint/5/angle_max: 1.58
joint/5/angle_min: -1.58
joint/5/angle_sgn: 1
joint/5/angle_scale: 0.001534
joint/5/angle_offset: 2045
