# Optical Flow Kalman Filter on Kawasaki IMU Board

/quadcopter_node/kalman_filter/XOpt/inputSigma: 0.06 #0.05
/quadcopter_node/kalman_filter/XOpt/biasSigma: 0.006 #0.005 test 0.002 good
/quadcopter_node/kalman_filter/XOpt/measureSigma: 0.1


/quadcopter_node/kalman_filter/YOpt/inputSigma: 0.06 #0.05
/quadcopter_node/kalman_filter/YOpt/biasSigma: 0.006 #0.005 test 0.002 good
/quadcopter_node/kalman_filter/YOpt/measureSigma: 0.1


/quadcopter_node/kalman_filter/ZOpt/inputSigma: 0.35
/quadcopter_node/kalman_filter/ZOpt/biasSigma: 0.0006
/quadcopter_node/kalman_filter/ZOpt/measureSigma: 0.01
