#Hydrus3 config
joint_state_sub_name: /hydrus3/joint_states

control_rate: 15.0
baselink: fc

only_three_axis_mode: false

q_roll: 400.0
q_roll_d: 40.0
q_roll_i: 10.0
q_pitch: 400.0
q_pitch_d: 40.0
q_pitch_i: 10.0

q_yaw: 50
strong_q_yaw: 100
q_yaw_d: 50.0
q_yaw_i: 0.4

q_z: 10.0
q_z_d: 10.0
q_z_i: 10.0

r1: 1.0
r2: 1.0
r3: 1.0
r4: 1.0
r5: 1.0

dist_thre: 0.04 # 0.04 is enough to calculate the planning, resulting in 0.07 ~ 0.08
f_max: 1000000.0#8.2
f_min: 0.0#2.0

yaw_pos_gain_sub_name: /velocity_control_gain_change