#Hydrus3 config

link_joint_offset: 0.205

link_base_center_mass: 0.241  # 0.238 + 0.0032(new battery holder)

link_joint_mass: 0.0785
controller1_mass: 0.022 # d_board is ligher than kduino(-2g)
controller2_mass: 0.104 #old: 0.093Kg(93g)
controller2_offset: 0.189 #old: 0.178

link_base_two_end_mass: 0.047 # 0.053 - 0.006(2leg)
link_num: 4

root_link: 2

link1_base_rod_mass: 0.105 

propeller1_direction: -1 #default: -1
propeller1_order: 0

link2_base_rod_mass: 0.1 

propeller2_direction: 1 #default: 1
propeller2_order: 1

link3_base_rod_mass: 0.094  

propeller3_direction: -1
propeller3_order: 2

link4_base_rod_mass: 0.094  

propeller4_direction: 1 #default :1
propeller4_order: 3

debug_log: false
debug2_log: false


lqi_thread_rate: 20.0
q_roll: 200.0  #  100
q_roll_d: 20.0  #  20
q_roll_i: 10.0 #  20
q_pitch: 200.0  #  100
q_pitch_d: 20.0  #  20
q_pitch_i: 10.0 #  20

q_yaw: 50 # 10 
strong_q_yaw: 10.0 # 10 
q_yaw_d: 50.0 #  10
q_yaw_i: 0.4 # 1

q_z: 10.0
q_z_d: 10.0
q_z_i: 10.0

r1: 1.0
r2: 1.0
r3: 1.0
r4: 1.0

dist_thre: 0.04 # 0.04 is enough to calculate the planning, resulting in 0.07 ~ 0.08
f_max: 1000000.0#8.2
f_min: 0.0#2.0

yaw_pos_gain_sub_name: /velocity_control_gain_change