aerial_robot_control_name: aerial_robot_control/under_act_body_rate/nmpc_controller

controller:
  nmpc:
    T_samp: 0.025  # 40 Hz  TODO: should be adjusted by main_rate
    T_pred: 2.0  # seconds
    T_integ: 0.1  # seconds

    n_states: 10
    n_controls: 4

    # constraint
    w_max: 6  # 1 rad/s ~ 57 deg/s
    w_min: -6
    c_max: 43.1  # 7 * 4 / 0.65  This value will be adjusted by physical constraints
    c_min: 0

    v_max: 1
    v_min: -1

    # params for the cost function
    Qp_xy: 300  # 0
    Qp_z: 400  # 500
    Qv_xy: 10  # 0
    Qv_z: 10  # 100
    Qq_xy: 10  # 400
    Qq_z: 100
    Rw: 10  # 10
    Rc: 5

    yaw_p_gain: 40.0  # temp
    yaw_d_gain: 1.0

    is_attitude_ctrl: true
    is_body_rate_ctrl: true


  # LQI gain generator
  lqi:
    gain_generate_rate: 15.0
    gyro_moment_compensation: true
    clamp_gain: true

    roll_pitch_p: 20
    roll_pitch_i: 0.5
    roll_pitch_d: 0.15

    yaw_p: 60
    yaw_i: 0.5
    yaw_d: 1.0

    r1: 1.0
    r2: 1.0
    r3: 1.0
    r4: 1.0

    trans_constraint_weight: 100
    att_control_weight: 1
