aerial_robot_control_name: aerial_robot_control/under_actuated_nmpc_lqi_controller

controller:

  # LQI gain generator
  lqi:
    gain_generate_rate: 15.0
    gyro_moment_compensation: true
    clamp_gain: true

    roll_pitch_p: 20
    roll_pitch_i: 0.5
    roll_pitch_d: 0.15

    yaw_p: 60
    yaw_i: 0.5
    yaw_d: 1.0

    r1: 1.0
    r2: 1.0
    r3: 1.0
    r4: 1.0

    trans_constraint_weight: 100
    att_control_weight: 1
