<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="dolphin_link" >

  <xacro:macro name="dolphin_link" params="parent self"> 

    <link name="${self}_front_junction">
      <visual>
        <geometry>
          <box size="0.01 ${tail_width} ${abdomen_height}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_front_junction_${self}_front_servo_rod_joint" type="fixed">
      <child link="${self}_front_servo_rod"/>
      <parent link="${self}_front_junction"/>
      <origin rpy="0 0 0" xyz="${-tail_len*.3+.005} 0 0"/>
    </joint>

    <link name="${self}_front_servo_rod_top">
      <visual>
        <geometry>
          <sphere radius="${servo_rod_radius*2}"/>
        </geometry>
        <material name="white">
          <color rgba="1 1 1 0.8"/>
        </material>
      </visual>
    </link>

    <joint name="${self}_front_servo_rod_top_${self}_front_servo_rod_joint" type="fixed">
      <parent link="${self}_front_servo_rod"/>
      <child link="${self}_front_servo_rod_top"/>
      <origin rpy="0 0 0" xyz="0 0 ${abdomen_height*.5}"/>
    </joint>

    <link name="${self}_front_servo_rod_bottom">
      <visual>
        <geometry>
          <sphere radius="${servo_rod_radius*2}"/>
        </geometry>
        <material name="white">
          <color rgba="1 1 1 0.8"/>
        </material>
      </visual>
    </link>

    <joint name="${self}_front_servo_rod_${self}_bottom_front_servo_rod_joint" type="fixed">
      <parent link="${self}_front_servo_rod"/>
      <child link="${self}_front_servo_rod_bottom"/>
      <origin rpy="0 0 0" xyz="0 0 -${abdomen_height*.5}"/>
    </joint>

    <link name="${self}_top_front_hinge_end">
      <visual>
        <geometry>
          <cylinder length="${tail_height}" radius="${tail_width*.5}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_top_front_hinge_end_${self}_front_servo_rod_joint" type="fixed">
      <parent link="${self}_front_servo_rod"/>
      <child link="${self}_top_front_hinge_end"/>
      <origin rpy="0 0 0" xyz="0 0 ${abdomen_height*.5-tail_height*.5}"/>
    </joint>

    <link name="${self}_bottom_front_hinge_end">
      <visual>
        <geometry>
          <cylinder length="${tail_height}" radius="${tail_width*.5}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_bottom_front_hinge_end_${self}_front_servo_rod_joint" type="fixed">
      <parent link="${self}_front_servo_rod"/>
      <child link="${self}_bottom_front_hinge_end"/>
      <origin rpy="0 0 0" xyz="0 0 ${-abdomen_height*.5+tail_height*.5}"/>
    </joint>

    <link name="${self}_top_front_hinge">
      <visual>
        <geometry>
          <box size="${tail_len*.3} ${tail_width} ${tail_height}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_top_front_hinge_${self}_top_front_hinge_end_joint" type="fixed">
      <parent link="${self}_top_front_hinge_end"/>
      <child link="${self}_top_front_hinge"/>
      <origin rpy="0 0 0" xyz="${tail_len*.15} 0 0"/>
    </joint>

    <link name="${self}_bottom_front_hinge">
      <visual>
        <geometry>
          <box size="${tail_len*.3} ${tail_width} ${tail_height}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_bottom_front_hinge_${self}_bottom_front_hinge_end_joint" type="fixed">
      <parent link="${self}_bottom_front_hinge_end"/>
      <child link="${self}_bottom_front_hinge"/>
      <origin rpy="0 0 0" xyz="${tail_len*.15} 0 0"/>
    </joint>


    <link name="${self}_front_servo_rod">
      <visual>
        <geometry>
          <cylinder length="${abdomen_height}" radius="${servo_rod_radius}"/>
        </geometry>
        <material name="white">
          <color rgba="1 1 1 0.8"/>
        </material>
      </visual>
    </link>

    <joint name="${self}_front_servo_rod_${self}_front_servo_joint" type="continuous">
      <child link="${self}_front_servo"/>
      <parent link="${self}_front_servo_rod"/>
      <origin xyz="${-tail_len*.3+.005} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <link name="${self}_front_servo">
      <visual>
        <geometry>
          <box size="${tail_len*.6} ${tail_len*.3} ${abdomen_height-tail_height*2}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
    </link>

    <joint name="${self}_front_servo_${self}_abdomen_joint" type="fixed">
      <child link="${self}_abdomen"/>
      <parent link="${self}_front_servo"/>
      <origin rpy="1.5708 0 0"
              xyz="${-abdomen_radius-tail_len-(tail_len*.6-tail_width-.01)*.5} 0 0"/> 
    </joint>

    <link name="${self}_front_servo_column">
      <visual>
        <geometry>
          <box size="${tail_width*.5} ${tail_width*.5} ${abdomen_height}"/> 
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_front_servo_column_${self}_front_servo_joint" type="fixed">
      <parent link="${self}_front_servo"/>
      <child link="${self}_front_servo_column"/>
      <origin rpy="1.5708 0 0" xyz="${-tail_len*.2} 0 0 "/>
    </joint>


    <link name="${self}_battery">
      <visual>
        <geometry>
          <box size="${tail_len*.6} ${tail_len*.35} ${tail_len*.25}"/>
        </geometry>
        <material name="blue">
          <color rgba="0 0 .8 0.8"/>
        </material>
      </visual>
    </link>

    <joint name="${self}_baterry_${self}_abdomen_joint" type="fixed">
      <parent link="${self}_abdomen"/>
      <child link="${self}_battery"/>
      <origin xyz="${abdomen_radius+tail_len*.4} 0 ${-abdomen_height*.5+tail_len*.125+tail_height}"/>
    </joint>

    <link name="${self}_front_bottom_tail">
      <visual>
        <geometry>
          <box size="${tail_len} ${tail_width} ${tail_height}"/> 
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_front_bottom_tail_${self}_abdomen_joint" type="fixed">
      <parent link="${self}_abdomen"/>
      <child link="${self}_front_bottom_tail"/>
      <origin rpy="0 0 0" xyz="${abdomen_radius+tail_len*.5} 0 ${-abdomen_height*.5+tail_height*.5}"/>
    </joint>

    <link name="${self}_front_top_tail">
      <visual>
        <geometry>
          <box size="${tail_len} ${tail_width} ${tail_height}"/> 
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_front_top_tail_${self}_abdomen_joint" type="fixed">
      <parent link="${self}_abdomen"/>
      <child link="${self}_front_top_tail"/>
      <origin rpy="0 0 0" xyz="${abdomen_radius+tail_len*.5} 0 ${abdomen_height*.5-tail_height*.5}"/>
    </joint>

    <link name="${self}_abdomen">
      <visual>
        <geometry>
          <cylinder length="${abdomen_height}" radius="${abdomen_radius}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <link name="${self}_rear_bottom_tail">
      <visual>
        <geometry>
          <box size="${tail_len} ${tail_width} ${tail_height}"/> 
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_rear_bottom_tail_${self}_abdomen_joint" type="fixed">
      <parent link="${self}_abdomen"/>
      <child link="${self}_rear_bottom_tail"/>
      <origin rpy="0 0 0" xyz="${-abdomen_radius-tail_len*.5} 0 ${-abdomen_height*.5+tail_height*.5}"/>
    </joint>

    <link name="${self}_rear_top_tail">
      <visual>
        <geometry>
          <box size="${tail_len} ${tail_width} ${tail_height}"/> 
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_rear_top_tail_${self}_abdomen_joint" type="fixed">
      <parent link="${self}_abdomen"/>
      <child link="${self}_rear_top_tail"/>
      <origin rpy="0 0 0" xyz="${-abdomen_radius-tail_len*.5} 0 ${abdomen_height*.5-tail_height*.5}"/>
    </joint>

    <link name="${self}_rear_junction">
      <visual>
        <geometry>
          <box size="0.01 ${tail_width} ${abdomen_height}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_rear_junction_${self}_abdomen_joint" type="fixed">
      <parent link="${self}_abdomen"/>
      <child link="${self}_rear_junction"/>
      <origin rpy="0 0 0" xyz="${-abdomen_radius-tail_len+.005} 0 0"/>
    </joint>

    <joint name="${parent}_${self}_joint" type="fixed">
      <parent link="${parent}_rear_junction"/>
      <child link="${self}_front_junction"/>
      <origin rpy="-1.5708  0 0" xyz="-0.01 0 0"/>
    </joint>

  </xacro:macro>

  <xacro:macro name="dolphin_end_link" params="parent self"> 

    <link name="${self}_front_junction">
      <visual>
        <geometry>
          <box size="0.01 ${tail_width} ${abdomen_height}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_front_junction_${self}_front_servo_rod_joint" type="fixed">
      <child link="${self}_front_servo_rod"/>
      <parent link="${self}_front_junction"/>
      <origin rpy="0 0 0" xyz="${-tail_len*.3+.005} 0 0"/>
    </joint>

    <link name="${self}_front_servo_rod_top">
      <visual>
        <geometry>
          <sphere radius="${servo_rod_radius*2}"/>
        </geometry>
        <material name="white">
          <color rgba="1 1 1 0.8"/>
        </material>
      </visual>
    </link>

    <joint name="${self}_front_servo_rod_top_${self}_front_servo_rod_joint" type="fixed">
      <parent link="${self}_front_servo_rod"/>
      <child link="${self}_front_servo_rod_top"/>
      <origin rpy="0 0 0" xyz="0 0 ${abdomen_height*.5}"/>
    </joint>

    <link name="${self}_front_servo_rod_bottom">
      <visual>
        <geometry>
          <sphere radius="${servo_rod_radius*2}"/>
        </geometry>
        <material name="white">
          <color rgba="1 1 1 0.8"/>
        </material>
      </visual>
    </link>

    <joint name="${self}_front_servo_rod_${self}_bottom_front_servo_rod_joint" type="fixed">
      <parent link="${self}_front_servo_rod"/>
      <child link="${self}_front_servo_rod_bottom"/>
      <origin rpy="0 0 0" xyz="0 0 -${abdomen_height*.5}"/>
    </joint>

    <link name="${self}_top_front_hinge_end">
      <visual>
        <geometry>
          <cylinder length="${tail_height}" radius="${tail_width*.5}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_top_front_hinge_end_${self}_front_servo_rod_joint" type="fixed">
      <parent link="${self}_front_servo_rod"/>
      <child link="${self}_top_front_hinge_end"/>
      <origin rpy="0 0 0" xyz="0 0 ${abdomen_height*.5-tail_height*.5}"/>
    </joint>

    <link name="${self}_bottom_front_hinge_end">
      <visual>
        <geometry>
          <cylinder length="${tail_height}" radius="${tail_width*.5}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_bottom_front_hinge_end_${self}_front_servo_rod_joint" type="fixed">
      <parent link="${self}_front_servo_rod"/>
      <child link="${self}_bottom_front_hinge_end"/>
      <origin rpy="0 0 0" xyz="0 0 ${-abdomen_height*.5+tail_height*.5}"/>
    </joint>

    <link name="${self}_top_front_hinge">
      <visual>
        <geometry>
          <box size="${tail_len*.3} ${tail_width} ${tail_height}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_top_front_hinge_${self}_top_front_hinge_end_joint" type="fixed">
      <parent link="${self}_top_front_hinge_end"/>
      <child link="${self}_top_front_hinge"/>
      <origin rpy="0 0 0" xyz="${tail_len*.15} 0 0"/>
    </joint>

    <link name="${self}_bottom_front_hinge">
      <visual>
        <geometry>
          <box size="${tail_len*.3} ${tail_width} ${tail_height}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_bottom_front_hinge_${self}_bottom_front_hinge_end_joint" type="fixed">
      <parent link="${self}_bottom_front_hinge_end"/>
      <child link="${self}_bottom_front_hinge"/>
      <origin rpy="0 0 0" xyz="${tail_len*.15} 0 0"/>
    </joint>


    <link name="${self}_front_servo_rod">
      <visual>
        <geometry>
          <cylinder length="${abdomen_height}" radius="${servo_rod_radius}"/>
        </geometry>
        <material name="white">
          <color rgba="1 1 1 0.8"/>
        </material>
      </visual>
    </link>

    <joint name="${self}_front_servo_rod_${self}_front_servo_joint" type="continuous">
      <child link="${self}_front_servo"/>
      <parent link="${self}_front_servo_rod"/>
      <origin xyz="${-tail_len*.3+.005} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <link name="${self}_front_servo">
      <visual>
        <geometry>
          <box size="${tail_len*.6} ${tail_len*.3} ${abdomen_height-tail_height*2}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
    </link>

    <joint name="${self}_front_servo_${self}_abdomen_joint" type="fixed">
      <child link="${self}_abdomen"/>
      <parent link="${self}_front_servo"/>
      <origin rpy="1.5708 0 0"
              xyz="${-tail_len*2-(tail_len*.6-tail_width-.01)*.5} 0 0"/> 
    </joint>

    <link name="${self}_front_servo_column">
      <visual>
        <geometry>
          <box size="${tail_width*.5} ${tail_width*.5} ${abdomen_height}"/> 
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_front_servo_column_${self}_front_servo_joint" type="fixed">
      <parent link="${self}_front_servo"/>
      <child link="${self}_front_servo_column"/>
      <origin rpy="1.5708 0 0" xyz="${-tail_len*.2} 0 0 "/>
    </joint>

    <link name="${self}_battery">
      <visual>
        <geometry>
          <box size="${tail_len*.6} ${tail_len*.35} ${tail_len*.25}"/>
        </geometry>
        <material name="blue">
          <color rgba="0 0 .8 0.8"/>
        </material>
      </visual>
    </link>

    <joint name="${self}_baterry_${self}_abdomen_joint" type="fixed">
      <parent link="${self}_abdomen"/>
      <child link="${self}_battery"/>
      <origin xyz="${tail_len*1.4} 0 ${-abdomen_height*.5+tail_len*.125+tail_height}"/>
    </joint>

    <link name="${self}_front_bottom_tail">
      <visual>
        <geometry>
          <box size="${tail_len*2} ${tail_width} ${tail_height}"/> 
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_front_bottom_tail_${self}_abdomen_joint" type="fixed">
      <parent link="${self}_abdomen"/>
      <child link="${self}_front_bottom_tail"/>
      <origin rpy="0 0 0" xyz="${tail_len} 0 ${-abdomen_height*.5+tail_height*.5}"/>
    </joint>

    <link name="${self}_front_top_tail">
      <visual>
        <geometry>
          <box size="${tail_len*2} ${tail_width} ${tail_height}"/> 
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_front_top_tail_${self}_abdomen_joint" type="fixed">
      <parent link="${self}_abdomen"/>
      <child link="${self}_front_top_tail"/>
      <origin rpy="0 0 0" xyz="${tail_len} 0 ${abdomen_height*.5-tail_height*.5}"/>
    </joint>

    <link name="${self}_abdomen">
      <visual>
        <geometry>
          <cylinder length="${abdomen_height}" radius="${tail_width*.5}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <link name="${self}_bottom_abdomen_rod">
      <visual>
        <geometry>
          <box size="${tail_width} ${tail_len*2} ${tail_height}"/> 
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_bottom_abdomen_rod_${self}_abdomen_joint" type="fixed">
      <parent link="${self}_abdomen"/>
      <child link="${self}_bottom_abdomen_rod"/>
      <origin rpy="0 0 0" xyz="0 0 ${-abdomen_height*.5+tail_height*.5}"/>
    </joint>

    <link name="${self}_top_abdomen_rod">
      <visual>
        <geometry>
          <box size="${tail_width} ${tail_len*2} ${tail_height}"/> 
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_top_abdomen_rod_${self}_abdomen_joint" type="fixed">
      <parent link="${self}_abdomen"/>
      <child link="${self}_top_abdomen_rod"/>
      <origin rpy="0 0 0" xyz="0 0 ${abdomen_height*.5-tail_height*.5}"/>
    </joint>

    <link name="${self}_left_semi_abdomen">
      <visual>
        <geometry>
          <cylinder length="${abdomen_height}" radius="${abdomen_radius}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_left_semi_abdomen_rod_${self}_abdomen_joint" type="fixed">
      <parent link="${self}_abdomen"/>
      <child link="${self}_left_semi_abdomen"/>
      <origin rpy="0 0 0" xyz="0 ${abdomen_radius+tail_len} 0"/>
    </joint>

    <link name="${self}_right_semi_abdomen">
      <visual>
        <geometry>
          <cylinder length="${abdomen_height}" radius="${abdomen_radius}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="${self}_right_semi_abdomen_rod_${self}_abdomen_joint" type="fixed">
      <parent link="${self}_abdomen"/>
      <child link="${self}_right_semi_abdomen"/>
      <origin rpy="0 0 0" xyz="0 ${-abdomen_radius-tail_len} 0"/>
    </joint>



    <joint name="${parent}_${self}_joint" type="fixed">
      <parent link="${parent}_rear_junction"/>
      <child link="${self}_front_junction"/>
      <origin rpy="-1.5708  0 0" xyz="-0.01 0 0"/>
    </joint>

  </xacro:macro>

</robot>
