control_plugin_name: control_plugin/hydrus_tilted_lqi_controller

controller:
  # z
  z:
    offset: 0
    limit: 16.5
    p_term_limit: 16.5
    i_term_limit: 16.5
    d_term_limit: 16.5
    landing_z_err_thresh: -0.55

  # xy
  xy:
    p_gain: 2.3 #2.3 #0.15 * g
    i_gain: 0.02 #0.002 * g
    hovering_i_gain: 0.02 #0.002 * g
    d_gain: 4.0 #0.4 * g
    limit: 3  # 0.3 * g
    p_term_limit: 3 #0.2 * g
    i_term_limit: 1.5 #0.15 * g
    d_term_limit: 3 #0.2 * g
    x_offset: 0
    y_offset: 0

  # yaw
  yaw:
    limit: 6.0
    p_term_limit: 4.5
    i_term_limit: 4.0
    d_term_limit: 4.0
    err_thresh: 0.4

  # LQI gain generator
  lqi:
    gain_generate_rate: 15.0
    gyro_moment_compensation: true
    clamp_gain: true

    q_roll: 1000
    q_roll_d: 100
    q_roll_i: 20.0
    q_pitch: 1000
    q_pitch_d: 100
    q_pitch_i: 10.0

    q_yaw: 100
    q_yaw_d: 50
    q_yaw_i: 0.5

    q_z: -3.6 # direct feedback gain, old: 10.0
    q_z_d: -3.4  # direct feedback gain, old: 20.0
    q_z_i: 1.55  # direct feedback gain, old: 10.0

    r1: 1.0
    r2: 1.0
    r3: 1.0
    r4: 1.0

    trans_constraint_weight: 100
    att_control_weight: 1

