#Dragon Quad config

joint_state_sub_name: /dragon/joint_states

verbose: true
control_rate: 15.0

baselink: fc

only_three_axis_mode: true

q_roll: 400 #650
q_roll_d: 40  #65
q_roll_i: 1.0
q_pitch: 400 #650
q_pitch_d: 40 #65
q_pitch_i: 1.0

q_yaw: 50
strong_q_yaw: 200
q_yaw_d:  50
q_yaw_i: 0.1

q_z: 20.0
q_z_d: 30.0
q_z_i: 20.0

r1: 1.0
r2: 1.0
r3: 1.0
r4: 1.0

var_thre: 0.1
f_max: 30.0
f_min: 10.0
edf_max_tilt: 0.0 # 0.1

# inverse kinematics
differential_motion_count: 50
thre_joint_vel: 0.1
w_joint_vel: 0.002
w_root_vel: 0.001
joint_vel_constraint_range: 0.11
joint_vel_forbidden_range: 0.02