# inverse kinematics
differential_kinematics_count: 200
actuator_state_sub_name: /dragon/joint_states
actuator_state_pub_name: /dragon/joint_states

# cost
differential_kinematics_cost:
        cartesian_constraint:
                verbose: true
                w_pos_err_constraint: 1.0
                w_att_err_constraint: 2.0
        state_vel:
                verbose: true
                w_joint_vel: 0.001
                w_root_translational_vel: 0.001 #0.005
                w_root_rotational_vel: 0.001 #0.005

# constraint
differential_kinematics_constraint:
        state_limit:
                verbose: true
                joint_vel_thre: 0.05 #0.17 , 0.02 is not valid for full_body
                root_translational_vel_thre: 0.1
                root_rotational_vel_thre: 0.05 # 0.17, 0.02 is not valid for full_body
                joint_vel_constraint_range: 0.11
                joint_vel_forbidden_range: 0.02
                vebose: true
        stability:
                verbose: true

stability_margin_thre: 0.3
f_max: 22.0
f_min: 14.0
