### PID control for quadcopter

controller/pitch/ctrl_loop_rate: 40
controller/roll/ctrl_loop_rate: 40
controller/throttle/ctrl_loop_rate: 40
controller/yaw/ctrl_loop_rate: 40

# throttle [N]
controller/throttle/pos_p_gain: -150.0  #0.25 * 1000
controller/throttle/pos_i_gain: 150.0 #250.0  #0.25 * 1000
controller/throttle/pos_d_gain: -180.0  #0.28 * 1000
controller/throttle/const_i_ctrl_thre_land: 0.0
controller/throttle/offset: 1100
controller/throttle/pos_limit: 1800
controller/throttle/pos_p_limit: 150
controller/throttle/pos_i_limit: 800
controller/throttle/pos_d_limit: 180

# yaw 
controller/yaw/pos_p_gain: -300.0 #0.45 * 1000
controller/yaw/pos_i_gain: 20.0 #0.02 * 1000
controller/yaw/pos_d_gain: 0.0
controller/yaw/pos_limit: 100
controller/yaw/pos_p_limit: 100
controller/yaw/pos_i_limit: 50
controller/yaw/pos_d_limit: 50
controller/yaw/vel_value_limit: 0
#controller/yaw/i_enable_limit: 0.25

# pitch [rad]
controller/pitch/pos_p_gain: 0.1 #0.2 
controller/pitch/pos_i_gain: 0.03 #
controller/pitch/pos_i_gain_hover: 0.005 #1.625 * PI / 10 / 180
controller/pitch/pos_d_gain: 0.12 #0.4
controller/pitch/vel_p_gain: 0.12 #0.4
controller/pitch/vel_i_gain: 0.005 #1.625 * PI / 10 / 180
controller/pitch/pos_limit: 0.3  # 17[deg]
controller/pitch/pos_p_limit: 0.2 
controller/pitch/pos_i_limit: 0.15
controller/pitch/pos_d_limit: 0.2
controller/pitch/offset: 0


#  roll [rad]
controller/roll/pos_p_gain: 0.1 #0.2 
controller/roll/pos_i_gain: 0.03
controller/roll/pos_i_gain_hover: 0.005
controller/roll/pos_d_gain: 0.12
controller/roll/vel_p_gain: 0.12
controller/roll/vel_i_gain: 0.005
controller/roll/pos_limit: 0.3
controller/roll/pos_p_limit: 0.2
controller/roll/pos_i_limit: 0.15
controller/roll/pos_d_limit: 0.2
controller/roll/offset: 0 
