# Sensor Fuser Loader
estimator:
        # sensor plugin
        sensor_list:
        - sensor_plugin/imu
        - sensor_plugin/mocap
        - sensor_plugin/gps
        - sensor_plugin/alt
        - sensor_plugin/optical_flow
        - sensor_plugin/vo

        # egomotion estimation
        egomotion_list:
        - kalman_filter/kf_pose_vel_acc_bias
        - kalman_filter/kf_pose_vel_acc_bias
        - kalman_filter/kf_pose_vel_acc_bias

        # experiment estimation
        experiment_list:
        - kalman_filter/kf_pose_vel_acc_bias
        - kalman_filter/kf_pose_vel_acc_bias
        - kalman_filter/kf_pose_vel_acc_bias

        # specific id(int) of sensor fuser, axis for kf
        fuser_egomotion_id1: 1 # 1 << 0
        fuser_egomotion_id2: 2 # 1 << 1
        fuser_egomotion_id3: 4 # 1 << 2
        fuser_experiment_id1: 1 # 1 << 0
        fuser_experiment_id2: 2 # 1 << 1
        fuser_experiment_id3: 4 # 1 << 2

        # specific name of sensor fuser
        fuser_egomotion_name1: /ee/x
        fuser_egomotion_name2: /ee/y
        fuser_egomotion_name3: /ee/z
        fuser_experiment_name1: /ex/x
        fuser_experiment_name2: /ex/y
        fuser_experiment_name3: /ex/z


# EGOMOTION_ESTIMATION_MODE = 0
# EXPERIMENT_MODE = 1
# GROUND_TRUTH_MODE = 2

/sensor_plugin:
        imu:
                estimate_mode: 3 # 1<<0 + 1<<1
        alt:
                estimate_mode: 1 # 1<<0
        gps:
                estimate_mode: 1 # 1<<0
        optical_flow:
                estimate_mode: 1 # 1<<0
        vo:
                estimate_mode: 1 # 1<<0
        mocap:
                estimate_mode: 6 # 1<<1 + 1<<2
